# 数据集构造
- 数据源：https://github.com/Meituan-Dianping/asap

In [1]:
import pandas as pd
import os
from pandas import DataFrame
from typing import Tuple


DIR_SOURCE = "/Users/wangfei/Documents/data/open_source_data/classification/asap-master/asap"
DIR_OUTPUT = "/Users/wangfei/Documents/project/server_multitask/data/origin"
# train.csv,eval.csv,test.csv

In [2]:
df_train = pd.read_csv(os.path.join(DIR_SOURCE, "train.csv"), encoding="utf-8")
df_test = pd.read_csv(os.path.join(DIR_SOURCE, "test.csv"), encoding="utf-8")
df_train

,id,review,star,Location#Transportation,Location#Downtown,Location#Easy_to_find,Service#Queue,Service#Hospitality,Service#Parking,Service#Timely,...,Price#Cost_effective,Price#Discount,Ambience#Decoration,Ambience#Noise,Ambience#Space,Ambience#Sanitary,Food#Portion,Food#Taste,Food#Appearance,Food#Recommend
0,46277,状元楼饭店第一次去，因为地理位置优越：在宁波市和义大道高、大、上，里面装修中式，菜是地道的宁...,5.0,1,1,1,-2,1,-2,-2,...,-2,-2,1,-2,-2,-2,-2,1,-2,-2
1,23691,我最爱他们家的猪手，麻辣鸡爪，肉片口磨，道道菜都是家常菜的味道，非常的好吃，是原来的昊烨，和...,5.0,1,-2,-2,-2,1,-2,-2,...,-2,-2,-2,-2,-2,1,-2,1,-2,-2
2,23660,我是比较喜欢荣新馆的，因为材料新鲜，服务又好，价格适中，但是老公每次吃都会拉肚子，特神奇，我...,4.0,-2,-2,-2,-2,1,-2,-2,...,-2,-2,-2,-2,-2,-2,-2,0,1,-2
3,379,8.8秒杀的多嘴肉蟹煲，第一天开业就去了，大众点评很给力，排了两个半小时的队才轮到，他家很年...,5.0,-2,-2,-2,-1,1,-2,-2,...,-2,1,-2,-2,-2,-2,1,1,-2,-2
4,13811,喜欢KOI好多年了，但是看着它的价格在一路飙涨，真心是有点越来越爱不起来了呢。不过还好有大众...,5.0,-2,1,-1,-2,-2,-2,-2,...,-2,1,-2,-2,-2,-2,1,1,-2,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36845,23873,才开的一个海鲜加工广场，商家很不错，老板娘和服务员都很热情，里面的加工价格也很合理，算是物美...,3.0,-2,-2,1,-2,1,-2,-2,...,1,-2,-2,-2,-2,-2,-2,1,-2,-2
36846,39467,这是在火车站附近发现的又一个便宜实惠的小店经常坐火车，不喜欢白天走，下午的火车到青岛基本上就...,5.0,1,-2,0,1,1,-2,-2,...,1,0,0,0,-2,1,-2,1,-2,1
36847,41667,靠窗最里的位置，角度不是很好但能看到浦江景也算不错了；芦笋沙拉很好吃，我点了份烟熏鲑鱼，口感...,4.0,-2,-2,-2,-2,-2,-2,-2,...,0,-2,-2,-1,-2,-2,-2,0,0,1
36848,38883,这家星巴克开在离家近，而且早上开的也早，所以经常会去吃早饭。环境还不错，还有露天位置，不过食...,1.0,-2,-2,-2,-2,-1,-2,-2,...,-2,-2,1,1,1,1,-2,-1,-2,-2
36849,39188,这家面包挺新鲜的，经常来买，特别推荐它家的乐活早餐，买任意一款面包加3元就有搭配饮料，三种选...,5.0,0,-2,-2,-2,-2,-2,-2,...,-2,0,1,1,1,1,-2,1,1,1

In [3]:
print(df_train["Location#Transportation"].value_counts())
print(df_train["Service#Queue"].value_counts())

-2    29501
 1     6605
-1      441
 0      303
Name: Location#Transportation, dtype: int64
-2    31306
 0     2122
 1     1845
-1     1577
Name: Service#Queue, dtype: int64

In [4]:
def data_builder(df: DataFrame) -> Tuple[DataFrame, DataFrame]:
    """Build Data
    1. Choose review for text
    2. Choose Location#Transportation & Service#Queue for two different task
    
    Args:
        df (DataFrame): Source Data
    Returns:
        df_location (DataFrame): Data of location label
        df_service (DataFrame): Data of service label
    """
    dict_location = {
        "text": list(df["review"]),
        "label": list(df["Location#Transportation"])
    }
    dict_service = {
        "text": list(df["review"]),
        "label": list(df["Service#Queue"])
    }
    df_location = DataFrame(dict_location)
    df_service = DataFrame(dict_service)
    print("DataFrame has [{}]rows & [{}]columns".format(df_service.shape[0], df_service.shape[1]))
    return df_location, df_service

In [5]:
df_location_train, df_service_train = data_builder(df_train)
df_location_test, df_service_test = data_builder(df_test)
df_service_test

DataFrame has [36850]rows & [2]columns
DataFrame has [4940]rows & [2]columns

                                                   text  label
0     和老公的朋友们聚餐，选择了这家烧肉屋，据说人气很旺，于是定座的，我们坐在楼上，阁楼感觉有点空...     -2
1     昨天晚上想找个安静的环境和同事谈工作，去了绿茵阁。我是第一次到该店，一进去感觉很温馨，环境优...     -2
2     以前听朋友说超级推荐 然后她又在野餐的时候买了这里的瘦身沙拉 我就更加期待 因为平时不在这一...     -2
3     看到大众点评网的推荐来试试看，在意大利餐厅吃泰国菜虽然说是创意泰菜，也只是摆盘更多变、时尚，...     -2
4     在清迈我唯一推荐的一家餐厅，非常非常正宗的泰北菜。叫做河岸餐厅顾名思义就在河边，我建议傍晚的...      0
...                                                 ...    ...
4935  家里有亲戚来北京玩，顺便来看我，也好长时间没有见了，我就带他们去吃了个饭，北京的餐饮是在太多...     -2
4936  哇!居然抽到了叶姐家的海鲜加工券，约了几个本地的经常吃原味海鲜的朋友，在一市场一顿哗啦啦的买...     -2
4937  和在其他城市吃过的台湾餐厅着实不同，大概是跟朝鲜人合伙开的~没有看到多少台式菜品，韩式的却着...     -2
4938  开了很久的店了，地铁站附近，一出来右转上个大斜坡石梯就到了。门口有停车位，但超时要收费。店家...     -2
4939  真是太给力了，上次不到20元的那个就抢到了，这次没想到又出现了，还是这么便宜，而且名额比上次...     -2

[4940 rows x 2 columns]

In [6]:
df_location_train.to_csv(os.path.join(DIR_OUTPUT, "location_train.csv"), encoding="utf-8", index=False)
df_location_test.to_csv(os.path.join(DIR_OUTPUT, "location_test.csv"), encoding="utf-8", index=False)
df_service_train.to_csv(os.path.join(DIR_OUTPUT, "service_train.csv"), encoding="utf-8", index=False)
df_service_test.to_csv(os.path.join(DIR_OUTPUT, "service_test.csv"), encoding="utf-8", index=False)

In [7]:
import pickle
from sklearn.preprocessing import LabelEncoder

def generate_label_encoder(df: DataFrame, label: str, save_path) -> LabelEncoder:
    """Generate Label Encoder & save to file

    Args:
        df (DataFrame): Train DataFrame
        label (str): Column Name of Label
        save_path ([type]): File Path to Save

    Returns:
        LabelEncoder: Label Encoder
    """
    if os.path.exists(save_path):
        return get_label_encoder(save_path)
    
    le = LabelEncoder()
    le.fit(df[label].tolist())
    output = open(save_path, 'wb')
    pickle.dump(le, output)
    return le

In [9]:
generate_label_encoder(df_location_train, "label", os.path.join(DIR_OUTPUT, "0_encoder.pkl"))
generate_label_encoder(df_service_train, "label", os.path.join(DIR_OUTPUT, "1_encoder.pkl"))

LabelEncoder()